amphibianecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core import views
from cart.views import ProductHomeView
from django_otp.admin import OTPAdminSite
from django.contrib.sitemaps.views import sitemap
from cart.sitemaps import ProductSitemap

sitemaps = {
    "products": ProductSitemap,
}

urlpatterns = [
    path('secret-admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', ProductHomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('shop/', include('cart.urls', namespace='cart')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('staff/', include('staff.urls', namespace='staff')),
    path('about/', views.AboutView.as_view(), name='about'),
    path('licences/', views.LicenceView.as_view(), name='licence'),
    path('terms-and-conditions/', views.TermsAndConditionsView.as_view(), name='terms-and-condition'),
    path('cookie-policy/', views.CookiePolicyView.as_view(), name='cookie-policy'),
    path('privacy-policy/', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('impressum/', views.ImpressumView.as_view(), name='impressum'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

admin.site.__class__ = OTPAdminSite
admin.site.site_title = "amphibian admin"
admin.site.site_header = "amphibian admin"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    # path('beats/', views.ProductListView.as_view(), name='product-list'),
    url(r'^search/$', views.product_list, name='product-list'),
    url(r'pdf/', views.receipt_view, name='receipt'),
    path('soundkits/', views.SoundkitListView.as_view(), name='soundkit-list'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('cart', views.CartView.as_view(), name='summary'),
    path('remove-from-cart/<pk>', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('orders/<pk>', views.OrderDetailView.as_view(), name='order-detail'),
]

cart/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django_countries.fields import CountryField
from .models import (
    OrderItem, LicenceVariation, Product, Address
)

User = get_user_model()


class AddToCartForm(forms.ModelForm):
    licence_variation = forms.ModelChoiceField(queryset=LicenceVariation.objects.none())

    class Meta:
        model = OrderItem
        fields = ['licence_variation']

    def __init__(self, *args, **kwargs):
        product_id = kwargs.pop('product_id')
        product = Product.objects.get(id=product_id)
        super().__init__(*args, **kwargs)

        self.fields['licence_variation'].queryset = product.licence_variation.all()


class AddressForm(forms.Form):
    shipping_address_line_1 = forms.CharField(required=False)
    shipping_address_line_2 = forms.CharField(required=False)
    shipping_zip_code = forms.CharField(required=False)
    shipping_city = forms.CharField(required=False)
    shipping_country = CountryField(default='CH').formfield()

    billing_address_line_1 = forms.CharField(required=False)
    billing_address_line_2 = forms.CharField(required=False)
    billing_zip_code = forms.CharField(required=False)
    billing_city = forms.CharField(required=False)
    billing_country = CountryField(default='CH').formfield()

    selected_shipping_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )
    selected_billing_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        user = User.objects.get(id=user_id)

        shipping_address_qs = Address.objects.filter(
            user=user,
            address_type='S'
        )
        billing_address_qs = Address.objects.filter(
            user=user,
            address_type='B'
        )

        self.fields['selected_shipping_address'].queryset = shipping_address_qs
        self.fields['selected_billing_address'].queryset = billing_address_qs

    def clean(self):
        data = self.cleaned_data

        selected_shipping_address = data.get('selected_shipping_address', None)
        if selected_shipping_address is None:
            if not data.get('shipping_address_line_1', None):
                self.add_error("shipping_address_line_1",
                               "Please fill in this field")
            if not data.get('shipping_address_line_2', None):
                self.add_error("shipping_address_line_2",
                               "Please fill in this field")
            if not data.get('shipping_zip_code', None):
                self.add_error("shipping_zip_code",
                               "Please fill in this field")
            if not data.get('shipping_city', None):
                self.add_error("shipping_city", "Please fill in this field")
            if not data.get('shipping_country', None):
                self.add_error("shipping_country", "Please fill in this field")

        selected_billing_address = data.get('selected_billing_address', None)
        if selected_billing_address is None:
            if not data.get('billing_address_line_1', None):
                self.add_error("billing_address_line_1",
                               "Please fill in this field")
            if not data.get('billing_address_line_2', None):
                self.add_error("billing_address_line_2",
                               "Please fill in this field")
            if not data.get('billing_zip_code', None):
                self.add_error("billing_zip_code",
                               "Please fill in this field")
            if not data.get('billing_city', None):
                self.add_error("billing_city", "Please fill in this field")
            if not data.get('billing_country', None):
                self.add_error("billing_country", "Please fill in this field")

cart/views.py
import json
import datetime
from django.conf import settings
from django.shortcuts import redirect, render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Product, OrderItem, Address, Payment, Order, LicenceVariation
from .utils import get_or_set_order_session
from django.shortcuts import get_object_or_404, reverse
from .forms import AddToCartForm, AddressForm
from django.contrib import messages
from django.http import JsonResponse
from .filters import ProductFilter, MyTagFilter

import io
from django.http import FileResponse


class ProductHomeView(generic.ListView):
    template_name = 'cart/home.html'
    queryset = Product.objects.all()
    context_object_name = 'products'
    ordering = ['-created']
    paginate_by = 12


def product_list(request):
    qs = Product.objects.all().order_by('-created')
    product_filter = ProductFilter(request.GET, queryset=qs)
    # tag_filter = MyTagFilter(request.GET, queryset=qs)
    return render(request, 'cart/product-list.html', {'filter': product_filter})


class SoundkitListView(generic.ListView):
    template_name = 'cart/soundkit-list.html'
    queryset = Product.objects.all()


class SoundkitDetailView(generic.FormView):
    template_name = 'cart/soundkit-detail.html'
    form_class = AddToCartForm

    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs['slug'])

    def get_success_url(self):
        return reverse("cart:summary")

    def get_form_kwargs(self):
        kwargs = super(SoundkitDetailView, self).get_form_kwargs()
        kwargs['product_id'] = self.get_object().id
        return kwargs

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        product = self.get_object()

        item_filter = order.items.filter(
            product=product,
            licence_variation=form.cleaned_data['licence_variation'],
        )
        if item_filter.exists():
            item = item_filter.first()
            item.save()

        else:
            new_item = form.save(commit=False)
            new_item.product = product
            new_item.order = order
            new_item.save()

        return super(SoundkitDetailView, self).form_valid(form)


class ProductDetailView(generic.FormView):
    template_name = 'cart/product-detail.html'
    form_class = AddToCartForm

    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs['slug'])

    def get_success_url(self):
        return reverse("cart:summary")

    def get_form_kwargs(self):
        kwargs = super(ProductDetailView, self).get_form_kwargs()
        kwargs['product_id'] = self.get_object().id
        return kwargs

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        product = self.get_object()

        item_filter = order.items.filter(
            product=product,
            licence_variation=form.cleaned_data['licence_variation'],
        )
        if item_filter.exists():
            item = item_filter.first()
            item.save()

        else:
            new_item = form.save(commit=False)
            new_item.product = product
            new_item.order = order
            new_item.save()

        return super(ProductDetailView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product'] = self.get_object()
        return context


class CartView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'cart/cart.html'

    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context


class RemoveFromCartView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect('cart:summary')


class CheckoutView(LoginRequiredMixin, generic.FormView):
    template_name = 'cart/checkout.html'
    form_class = AddressForm

    def get_success_url(self):
        return reverse("cart:payment")

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        selected_shipping_address = form.cleaned_data.get(
            'selected_shipping_address')
        selected_billing_address = form.cleaned_data.get(
            'selected_billing_address')

        if selected_shipping_address:
            order.shipping_address = selected_shipping_address
        else:
            address = Address.objects.create(
                address_type='S',
                user=self.request.user,
                address_line_1=form.cleaned_data['shipping_address_line_1'],
                address_line_2=form.cleaned_data['shipping_address_line_2'],
                zip_code=form.cleaned_data['shipping_zip_code'],
                city=form.cleaned_data['shipping_city'],
            )
            order.shipping_address = address

        if selected_billing_address:
            order.billing_address = selected_billing_address
        else:
            address = Address.objects.create(
                address_type='B',
                user=self.request.user,
                address_line_1=form.cleaned_data['billing_address_line_1'],
                address_line_2=form.cleaned_data['billing_address_line_2'],
                zip_code=form.cleaned_data['billing_zip_code'],
                city=form.cleaned_data['billing_city'],
            )
            order.billing_address = address

        order.save()
        messages.info(
            self.request, "You have successfully added your addresses")
        return super(CheckoutView, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        kwargs["user_id"] = self.request.user.id
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context


class PaymentView(generic.TemplateView):
    template_name = 'cart/payment.html'

    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        context["PAYPAL_CLIENT_ID"] = settings.PAYPAL_CLIENT_ID
        context['order'] = get_or_set_order_session(self.request)
        context["CALLBACK_URL"] = reverse('cart:thank-you')
        return context


class ConfirmOrderView(generic.View):
    def post(self, request, *args, **kwargs):
        order = get_or_set_order_session(request)
        body = json.loads(request.body)
        payment = Payment.objects.create(
            order=order,
            successful=True,
            raw_response=json.dumps(body),
            amount=float(body["purchase_units"][0]["amount"]["value"]),
            payment_method='PayPal'
        )
        order.ordered = True
        order.ordered_date = datetime.date.today()
        order.save()
        order_jsn = json.dumps(order)
        return JsonResponse({"data": "success"})


class ThankYouView(generic.TemplateView):
    template_name = 'cart/thanks.html'


class OrderDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'order.html'
    queryset = Order.objects.all()
    context_object_name = 'order'


def receipt_view(request):
    # Create a file-like buffer to receive PDF data
    buffer = io.BytesIO()

    # Create the PDF object, using the buffer as its "file".
    p = canvas.Canvas(buffer)

    # Draw things on the pdf. Here's where the PDF generation happens.
    p.drawString(100, 100, "Hello World")

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    # FilResponse sets the Content-Disposition header so that browsers
    # present the option to save the file
    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename='hello.pdf')

templates/cart/cart.html
{% extends "base.html" %}
{% block head_title %}
cart - amphibian.ch
{% endblock %}

{% block extra_head %}
<meta name="description" property="og:description" content="Your cart on amphibian.ch. Continue to checkout to complete
your order">
{% endblock extra_head %}

{% block content %}

<div class="">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">home</a>
                <span class="mx-2 mb-0 span-divider">/</span>
                <strong class="current-page">cart</strong>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="col-sm-12 w-100">
        <table class="table">
            <thead>
            <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Licence</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
                {% for item in order.items.all %}
                <tr>
                    <td class="product-name">
                        {{ item.product.title }}
                    </td>
                    <td>
                        ${{ item.get_total_item_price }}
                    </td>
                    <td>
                        {{ item.licence_variation.name}}
                    </td>
                    <td>
                        <a href="{% url 'cart:remove-from-cart' item.id %}" class="btn btn-sm amphibian-button-secondary">X</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colSpan='12' class="text-center">
                        There are no items in  your cart. <a href="{% url 'cart:product-list' %}" class="btn py-3 btn-sm
                         amphibian-button-secondary">Continue Shopping</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% if order.items.count > 0 %}
        <div class="row">
            <div class="col-md-6">
                <div class="row md-5">
                    <div class="col-md-12">
                        <a class="btn py-3 btn-sm btn-block amphibian-button-secondary" href="{% url 'cart:product-list' %}">Continue Shopping</a>
                    </div>
                </div>
                <br>
            </div>
            <div class="col-md-6">
                <div class="row justify-content-end">
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3>Cart Totals</h3>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <div class="col-md-6">
                                <span id="subtotal-title">Subtotal</span>
                            </div>
                            <div class="col-md-6 text-right" id="subtotal-amount">
                                ${{ order.get_subtotal }}
                            </div>
                        </div>
                        <div class="row mb-5">
                            <div class="col-md-6">
                                <span> <p>Total</span></p>
                            </div>
                            <div class="col-md-6 text-right">
                                <p>${{ order.get_total }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <a href="{% url 'cart:checkout' %}" class="btn bt-lg py-3 btn-block amphibian-button-primary button-a">Proceed to checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
<br>
{% endblock content %}

templates/cart/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_title %}
checkout - amphibian.ch
{% endblock %}
{% block extra_head %}
<meta name="description" property="og:description" content="Checkout your order and continue to our payment site to
complete your order">

{% endblock extra_head %}


{% block content %}

<div class="">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">home</a>
                <span class="mx-2 mb-0 span-divider">/</span>
                <a class="" href="{% url 'cart:summary' %}">cart</a>
                <span class="mx-2 mb-0 span-divider">/</span>
                <strong class="current-page">checkout</strong>
            </div>
        </div>
    </div>
</div>
<br>
<div class="site-section">
    <div class="container">
        {% if not request.user.is_authenticated %}
        <div class="row mb-5">
            <div class="col-md-12">
                <div class="border p-4 rounded" role="alert">
                    You are nearly finished with your order. To finalize with your order, plase <a href="">Login</a> or
                    <a>Signup</a>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: 90%;" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">90% complete</div>
                </div>
            </div>
        </div>
        {% else %}
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6 mb-5 mb-md-0">
                    <h2 class="h3 mb-3 text-black text-center" id="billing-details">Billing Details</h2>
                    <hr />
                    {{ form|crispy }}
                    <div class="form-group">
                        <button type="submit" class="btn btn-lg py-3 btn-block amphibian-button-primary">
                            Proceed to payment
                        </button>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row md-5">
                        <div class="col-md-12">
                            <h2 class="h3 mb-3 text-black text-center" id="your-order">Your Order</h2>
                            <hr>
                            <div class="p-3 p-lg-5">
                                <table class="table site-block-order-table mb-5">
                                    <thead>
                                        <tr>
                                            <th class="font-normal-white">Product</th>
                                            <th class="font-normal-white">Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for item in order.items.all %}
                                        <tr>
                                           <td class="font-medium-white">
                                               {{ item.product.title }}, {{ item.licence_variation.name }}
                                                <strong class="mx-2 font-medium-white">1x</strong>
                                            </td>
                                            <td class="font-medium-white">
                                                ${{ item.get_total_item_price }}
                                            </td>
                                        </tr>
                                        </tr>
                                    {% endfor %}
                                    <tr>
                                        <td>
                                            <strong id="subtotal">Subtotal</strong>
                                            <td>${{ order.get_subtotal }}</td>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <strong class="text-black">Order total</strong>
                                        <td>
                                            <strong class="text-black font-weight-bold">${{ order.get_total }}</strong></td>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        {% endif %}
    </div>
</div>
<br>
{% endblock content %}

templates/cart/home.html
{% extends "base.html" %}

{% block head_title %}
home - amphibian.ch
{% endblock %}

{% block extra_head %}
<meta name="description" property="og:description" content="Find the best beats and soundkits">

<meta property="og:url" content="https://www.amphibian.ch" />
<meta property="og:title" content="Buy beats online" />
<meta property="og:image" content="https://janowski.dev/static/cover.png" />
<meta property="og:image:alt" content="Amphibian.ch Logo" />


<meta name="twitter:image" content="https://www.amphibian.ch" />
<meta property="twitter:image:alt" content="amphibian.ch" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="amphibian.ch" />
{% endblock extra_head %}

{% block content %}

<h1 class="title-h1">amphibian</h1>
<br>
<div class="container">
    <div class="row text-center">
        <div class="col-lg-12 text-center">
            <p class="info-text">
                Welcome to amphibian. Checkout our beats and soundkits.
                <br>
                Check out our <a href="{% url 'licence' %}" class="highlighted-anchor">licence page</a> for information about our pricing
            </p>
        </div>
    </div>
</div>
<br>
<div class="container">
      <div class="row">
          {% for product in products %}
          {% if not product.is_soundkit %}
          <div class="col-lg-3 text-center">
              <a href="{{ product.get_absolute_url }}">
                  <img src="{{product.image.url}}" alt="beat-cover" class="img-fluid img-cover element-shadow">
              </a>
              <a href="{{ product.get_absolute_url }}" >
                  <h3 id="title-link">{{ product.title }}</h3>
              </a>
              <br>
          </div>
          {% endif %}
          {% endfor %}
      </div>
    <div class="row">
        <div class="mx-auto">
            <button class="btn btn-lg py-3 btn-block amphibian-button-primary discover-more element-shadow text-decoration-none">
                <a href="{% url 'cart:product-list' %}" class="discover-more-anchor">
                    discover more
                </a>
            </button>
            <br>
        </div>
    </div>
</div>
{% endblock %}

templates/cart/payment.html
{% extends "base.html" %}

{% block head_title %}
payment - amphibian.ch
{% endblock %}

{% block extra_head %}
<meta name="description" property="og:description" content="Select your payment option to complete your order.">

{% endblock extra_head %}
{% block content %}

<style>
    .lds-facebook {
      display: inline-block;
      position: relative;
      width: 80px;
      height: 80px;
    }
    .lds-facebook div {
      display: inline-block;
      position: absolute;
      left: 8px;
      width: 16px;
      background: #fff;
      animation: lds-facebook 1.2s cubic-bezier(0, 0.5, 0.5, 1) infinite;
    }
    .lds-facebook div:nth-child(1) {
      left: 8px;
      animation-delay: -0.24s;
    }
    .lds-facebook div:nth-child(2) {
      left: 32px;
      animation-delay: -0.12s;
    }
    .lds-facebook div:nth-child(3) {
      left: 56px;
      animation-delay: 0;
    }
    @keyframes lds-facebook {
      0% {
        top: 8px;
        height: 64px;
      }
      50%, 100% {
        top: 24px;
        height: 32px;
      }
    }
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="alert alert-success text-center" role="alert" id="alertSuccess" style="display: none;">
                Your payment was successful.
            </div>
            <div class="alert alert-danger text-center" role="alert" id="alertFailure" style="display: none;">
                Your payment failed. Please try again.
            </div>
            <div class="text-center py-3">
                <div id="loader" style="margin: auto; display: none;" class="lds-facebook">
                    <div>

                    </div>
                    <div>

                    </div>
                    <div>

                    </div>
                </div>
            </div>

            <div id="paymentInfo">
                <h2 class="font-normal-white">Order total: ${{ order.get_total }}</h2>
                <h4>Select a payment method</h4>
                <div id="paypal-button-container">
                </div>
            </div>
            <hr class="horizontal-divider">
            <div>
                <a href="{% url 'cart:checkout' %}">
                    <p>go back to checkout</p>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}


{% block scripts %}

<script
        src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_CLIENT_ID }}"> // Required. Replace SB_CLIENT_ID with your sandbox client ID.
</script>

<script>
    const loader = document.getElementById('loader');
    const paymentInfo = document.getElementById('paymentInfo');

    function toggleLoader(on) {
        loader.style.display = on === true ? "block" : "none";
        paymentInfo.style.display = on === true ? "none" : "block";
    }

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            let cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                let cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    let csrftoken = getCookie('csrftoken');

    function sendOrderConfirmed(details) {
        return fetch("{% url 'cart:confirm-order' %}", {
            method: "post",
            body: JSON.stringify(details),
            headers: {
                "Content-Type": "application/json",
                "X-CSRFToken": csrftoken
            }
        })
    }

    paypal.Buttons({
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: '{{ order.get_total }}'
              }
            }]
          });
        },
        onApprove: function(data, actions) {
            toggleLoader(true)
            return actions.order.capture().then(function(details) {
                sendOrderConfirmed(details).then(res =>{
                    toggleLoader(false);
                    const alertSuccess = document.getElementById('alertSuccess');
                    alertSuccess.style.display = "block";
                    setTimeout(function() {
                    window.location.replace("{{ CALLBACK_URL }}")
                    }, 3000);
                })
            })
            .catch(err => {
                    const alertFailure = document.getElementById('alertFailure');
                    alertFailure.style.display = 'block';
                })
            .finally(() => toggleLoader(false));
        }
     }).render('#paypal-button-container');
</script>

{% endblock scripts %}

templates/cart/thanks.html
{% extends 'base.html' %}

{% block head_title %}
thanks - amphibian.ch
{% endblock %}

{% block extra_head %}
<meta name="description" property="og:description" content="Thank you for shopping at amphibian.ch">
{% endblock extra_head %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h2>Thank you for shopping at amphibian</h2>
            <br>
            <p class="info-text">Your files are now available at your <a href="{% url 'profile' %}" class="highlighted-anchor">profile page.</a>  If they do not show up, please contact us.</p>
            <p class="info-text">We hope to welcome you back soon on amphibian.ch</p>
        </div>
    </div>
</div>

{% endblock content %}