amphibianecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core import views
from cart.views import ProductHomeView
from django_otp.admin import OTPAdminSite
from django.contrib.sitemaps.views import sitemap
from cart.sitemaps import ProductSitemap

sitemaps = {
    "products": ProductSitemap,
}

urlpatterns = [
    path('secret-admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', ProductHomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('shop/', include('cart.urls', namespace='cart')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('staff/', include('staff.urls', namespace='staff')),
    path('about/', views.AboutView.as_view(), name='about'),
    path('licences/', views.LicenceView.as_view(), name='licence'),
    path('terms-and-conditions/', views.TermsAndConditionsView.as_view(), name='terms-and-condition'),
    path('cookie-policy/', views.CookiePolicyView.as_view(), name='cookie-policy'),
    path('privacy-policy/', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('impressum/', views.ImpressumView.as_view(), name='impressum'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

admin.site.__class__ = OTPAdminSite
admin.site.site_title = "amphibian admin"
admin.site.site_header = "amphibian admin"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    # path('beats/', views.ProductListView.as_view(), name='product-list'),
    url(r'^search/$', views.product_list, name='product-list'),
    url(r'pdf/', views.receipt_view, name='receipt'),
    path('soundkits/', views.SoundkitListView.as_view(), name='soundkit-list'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('cart', views.CartView.as_view(), name='summary'),
    path('remove-from-cart/<pk>', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('orders/<pk>', views.OrderDetailView.as_view(), name='order-detail'),
]

staff/urls.py
from . import views
from django.urls import path


app_name = 'staff'

urlpatterns = [
    path('', views.StaffView.as_view(), name='staff'),
    path('create/', views.ProductCreateView.as_view(), name='product-create'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<pk>/delete', views.ProductDeleteView.as_view(), name='product-delete'),
    path('products/<pk>/update', views.ProductUpdateView.as_view(), name='product-update')
]

staff/models.py
from django.db import models

# Create your models here.

staff/forms.py
from django import forms

from cart.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'title',
            'image',
            'description',
            'licence_variation'
        ]

staff/views.py
from django.shortcuts import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from cart.models import Order, Product
from .mixins import StaffUserMixin
from .forms import ProductForm


class StaffView(LoginRequiredMixin, StaffUserMixin, generic.ListView):
    template_name = 'staff/staff.html'
    queryset = Order.objects.filter(ordered=True).order_by('-ordered_date')
    paginate_by = 5
    context_object_name = 'orders'


class ProductListView(LoginRequiredMixin, StaffUserMixin, generic.ListView):
    template_name = 'staff/product-list.html'
    queryset = Product.objects.all()
    paginate_by = 20
    context_object_name = 'products'


class ProductCreateView(LoginRequiredMixin, StaffUserMixin, generic.CreateView):
    template_name = 'staff/product-create.html'
    form_class = ProductForm

    def get_success_url(self):
        return reverse("staff:product-list")

    def form_valid(self, form):
        form.save()
        return super(ProductCreateView, self).form_valid(form)


class ProductDeleteView(LoginRequiredMixin, StaffUserMixin, generic.DeleteView):
    template_name = 'staff/product-delete.html'
    queryset = Product.objects.all()

    def get_success_url(self):
        return reverse("staff:product-list")


class ProductUpdateView(LoginRequiredMixin, StaffUserMixin, generic.UpdateView):
    template_name = 'staff/product-update.html'
    form_class = ProductForm
    queryset = Product.objects.all()
    paginate_by = 20

    def get_success_url(self):
        return reverse("staff:product-list")

    def form_valid(self, form):
        form.save()
        return super(ProductUpdateView, self).form_valid(form)

templates/staff/product-create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2>Staff Portal - Create a product</h2>
                <a href="{% url 'staff:product-list' %}">Go back to staff</a>
                <hr/>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class='btn btn-primary'>Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/staff/product-delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class='btn btn-primary'>Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/staff/product-list.html
{% extends "base.html" %}
{% block content %}
<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2>Staff Portal - Product</h2>
                <div class="">
                    <div class="">
                        <h5>{{ request.user.email }}
                            <a href="{% url 'account_logout' %}"><small class="float-right">Logout</small></a>
                        </h5>
                        <a href="{% url 'staff:product-create' %}">Create a product</a>
                        <hr />
                        <h5 class="">
                            Recent Orders
                        </h5>
                        <div class="">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for product in products %}
                                <tr>
                                    <td>{{ product.title }}</td>
                                    <td>
                                        <a href="{{ product.get_update_url }}">Update</a>
                                        <a tabindex="0"
                                           class="btn btn-sm amphibian-button-secondary"
                                           role='button'
                                           data-html='true'
                                           data-toggle='popover'
                                           data-trigger='focus'
                                           href='{{ product.get_delete_url }}'
                                        >
                                            Delete
                                        </a>
                                        </td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="4">You don't have any products</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {% if page_obj.has_other_pages %}
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="site-block-27">
                                    <ul>
                                        {% if page_obj.has_previous %}
                                        <li><a href="?page={{page_obj.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                        {% endif %}

                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                            <li class="active"><span>{{ i }}<span class="sr-only">(current)</span></span></li>
                                            {% else %}
                                            <li><a href="?page={{ i }}">{{i}}</a></li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                        <li><a href="?page={{page_obj.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                        <li class="disabled"><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    $(function () {
        $("[data-toggle=popover]").popover();
    });
</script>
{% endblock scripts %}

templates/staff/product-update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2>Staff Portal - update a product</h2>
                <a href="{% url 'staff:product-list' %}">Go back to staff</a>
                <hr/>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type='submit' class='btn amphibian-button-primary'>Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/staff/staff.html
{% extends "base.html" %}
{% block content %}
<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2>Staff Portal</h2>
                <div class="">
                    <div class="">
                        <h5>{{ request.user.email }}
                            <a href="{% url 'account_logout' %}"><small class="float-right">Logout</small></a>
                        </h5>
                        <a href="{% url 'staff:product-list' %}">Product Listview</a>
                        <hr />
                        <h5 class="">
                            Recent Orders
                        </h5>
                        <div class="site-block-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Reference No.</th>
                                        <th>Date</th>
                                        <th>User</th>
                                        <th>Amount</th>
                                        <th>Payment Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for order in orders %}
                                <tr>
                                    <td><a href="{% url 'cart:order-detail' order.pk %}">#{{order.reference_number }}</a></td>
                                    <td>{{ order.ordered_date }}</td>
                                    <td>{{ order.user.email }}</td>
                                    <td>${{ order.get_total }}</td>
                                    <td>{% if order.ordered %}Paid{% else %}Not paid{% endif %}</td>
                                </tr>
                                {% empty %}
                                <tr>
                                    <td colspan="3">You haven't made any orders</td>
                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        {% if page_obj.has_other_pages %}
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <div class="site-block-27">
                                    <ul>
                                        {% if page_obj.has_previous %}
                                        <li><a href="?page={{page_obj.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                        <li class="disabled"><span>&laquo;</span></li>
                                        {% endif %}

                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                            <li class="active"><span>{{ i }}<span class="sr-only">(current)</span></span></li>
                                            {% else %}
                                            <li><a href="?page={{ i }}">{{i}}</a></li>
                                            {% endif %}
                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                        <li><a href="?page={{page_obj.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                        <li class="disabled"><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}