amphibianecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core import views
from cart.views import ProductHomeView
from django_otp.admin import OTPAdminSite
from django.contrib.sitemaps.views import sitemap
from cart.sitemaps import ProductSitemap

sitemaps = {
    "products": ProductSitemap,
}

urlpatterns = [
    path('secret-admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', ProductHomeView.as_view(), name='home'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('shop/', include('cart.urls', namespace='cart')),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('staff/', include('staff.urls', namespace='staff')),
    path('about/', views.AboutView.as_view(), name='about'),
    path('licences/', views.LicenceView.as_view(), name='licence'),
    path('terms-and-conditions/', views.TermsAndConditionsView.as_view(), name='terms-and-condition'),
    path('cookie-policy/', views.CookiePolicyView.as_view(), name='cookie-policy'),
    path('privacy-policy/', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('impressum/', views.ImpressumView.as_view(), name='impressum'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

admin.site.__class__ = OTPAdminSite
admin.site.site_title = "amphibian admin"
admin.site.site_header = "amphibian admin"

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    # path('beats/', views.ProductListView.as_view(), name='product-list'),
    url(r'^search/$', views.product_list, name='product-list'),
    url(r'pdf/', views.receipt_view, name='receipt'),
    path('soundkits/', views.SoundkitListView.as_view(), name='soundkit-list'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('confirm-order/', views.ConfirmOrderView.as_view(), name='confirm-order'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('cart', views.CartView.as_view(), name='summary'),
    path('remove-from-cart/<pk>', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('orders/<pk>', views.OrderDetailView.as_view(), name='order-detail'),
]

staff/urls.py
from . import views
from django.urls import path


app_name = 'staff'

urlpatterns = [
    path('', views.StaffView.as_view(), name='staff'),
    path('create/', views.ProductCreateView.as_view(), name='product-create'),
    path('products/', views.ProductListView.as_view(), name='product-list'),
    path('products/<pk>/delete', views.ProductDeleteView.as_view(), name='product-delete'),
    path('products/<pk>/update', views.ProductUpdateView.as_view(), name='product-update')
]

templates/about.html
{% extends "base.html" %}
{% block head_title %}
about - amphibian.ch
{% endblock %}

{% block extra_head %}
<meta name="description" property="og:description" content="About amphibian.ch">
{% endblock extra_head %}

{% block content %}

<div class="container">
    <h2>about</h2>
</div>

<div class="">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">home</a>
                <span class="mx-2 mb-0 span-divider">/</span>
                <strong class="current-page">about</strong>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-7 text-center">
            <h2>origins</h2>
            <p>Amphibian.ch was founded in 2020 by three friends in Switzerland. We have been making music together for
                several years. Together we are a well-rehearsed team, in which each of us can play out his qualities.
            </p>
            <br>
            <p>
                For us amphibian.ch is a platform to express our love for music. We also welcome artists and other music
                producers in our studio to express our love for music.
            </p>

        </div>
    </div>
</div>
<br>
{% endblock %}

templates/base.html
{% load static %}
{% load cart_template_tags %}
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap"
      rel="stylesheet"
    />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link rel="stylesheet" type='text/css' href="{% static 'style.css'%}" />
    <title>{% block head_title %}{% endblock %}</title>
    <meta name="keywords" content="hip-hop, buy beats, trap, R'n'B, buy music online, download beats, rap beats, tracks, amphibian, music">
    {% block extra_head %}
    {% endblock %}
</head>

<body>
<wrapper class="d-flex flex-column">
    <nav class="navbar navbar-expand navbar-dark">
          <div class="navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                  {% if user.is_authenticated and not user.is_staff %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'home' %}"
                      >home</a>
                  </li>
                  <li class="nav-item text-center">
                      <a class="nav-link" href="{% url 'cart:product-list' %}">beats</a>
                  </li>
                  <li class="nav-item text-center">
                      <a class="nav-link" href="{% url 'cart:soundkit-list' %}">soundkits</a>
                  </li>
                  <li class="nav-item text-center">
                      <a class="nav-link" href="{% url 'profile' %}">profile</a>
                  </li>
                  <li class="nav-item cart-navbar align-items-center">
                      <a href="{% url 'cart:summary'%}" class="cart-field-navbar">
                          <span class="material-icons shopping-cart-item">
                              shopping_cart
                          </span>
                          <span class="cart-item-count">{{ request|cart_item_count }}</span>
                      </a>
                  </li>
                  {% elif request.user.is_staff %}

                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'home' %}"
                          >home</a>
                  </li>
                  <li class="nav-item text-center">
                      <a class="nav-link" href="{% url 'cart:product-list' %}">beats</a>
                  </li>
                  <li class="nav-item text-center">
                      <a class="nav-link" href="{% url 'cart:soundkit-list' %}">soundkits</a>
                  </li>
                  <li class="nav-item text-center">
                      <a href="{% url 'staff:staff' %}" class="nav-link header-link">staff</a>
                  </li>

                  {% else %}

                  <li class="nav-item" id="header-link">
                      <a class="nav-link" href="{% url 'home' %}"
                          >home</a>
                  </li>
                  <li class="nav-item text-center">
                      <a class="nav-link " href="{% url 'cart:product-list' %}">beats</a>
                  </li>
                  <li class="nav-item text-center">
                      <a class="nav-link" href="{% url 'cart:soundkit-list' %}">soundkits</a>
                  </li>
                  <li class="nav-item text-center">
                      <a class="nav-link" href="{% url 'account_login' %}">login</a>
                  </li>
                  <li>
                      <i class="fas fa-shopping-cart" id="my-cart"></i>
                  </li>
                  {% endif %}
              </ul>
          </div>
    </nav>
    <main class="flex-fill">
        {% block content %}
        {% endblock %}
    </main>
    <div class="footer">
        <footer class="page-footer">
          <div class="container text-center text-md">
              <div class="row">
                  <div class="col-md-12 mx-auto">
                      <h5 class="font-weight-bold mt-3 mb-4" id="footer-title">amphibian.ch</h5>
                      <ul class="list-unstyled">
                          <li>
                              <a href="{% url 'about' %}" class="footer-a">about</a>
                          </li>
                          <li>
                              <a href="{% url 'contact' %}" class="footer-a">contact</a>
                           </li>
                          <li>
                              <a href="{% url 'licence' %}" class="footer-a">licences</a>
                          </li>
                          <li>
                              <a href="{% url 'terms-and-condition' %}" class="footer-a">terms and conditions</a>
                          </li>
                          <li>
                              <a href="{% url 'cookie-policy' %}" class="footer-a">cookie policy</a>
                          </li>
                          <li>
                              <a href="{% url 'privacy-policy' %}" class="footer-a">privacy policy</a>
                          </li>
                          <li>
                              <a href="{% url 'impressum' %}" class="footer-a">impressum</a>
                          </li>
                      </ul>
                  </div>
                  <hr class="clearfix w-100 d-md-none">
              </div>
          </div>
          <div class="footer-copyright text-center py-3">
              <h4 id="copyright">© 2020 fabian haefliger, version 1.1</h4>
          </div>
      </footer>
    </div>
</wrapper>

{% include 'scripts.html' %}
{% block scripts %}
{% endblock scripts %}
</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}
contact - amphibian.ch
{% endblock %}

{% block extra_head %}
<meta name="description" property="og:description" content="Get in contact with amphibian.ch">
{% endblock extra_head %}

{% block content %}

<div class="container">
    <h2>contact</h2>
</div>

<div class="">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0 span-divider">/</span>
                <strong class="current-page">Contact</strong>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-7">
            <h2>Get in touch</h2>
        </div>
        <div class="col-md-7">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-lg btn-block amphibian-button-primary">
            </form>
        </div>

    </div>
    <br>
</div>


{% endblock %}

templates/cookie-policy.html
{% extends "base.html" %}
{% block head_title %}
cookie-policy - amphibian.ch
{% endblock %}

{% block extra_head %}
<meta name="description" property="og:description" content="Get to know about our cookie policy">
{% endblock extra_head %}

{% block content %}

<div class="container">
    <h2>cookie policy</h2>
</div>

<div class="">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">Home</a>
                <span class="mx-2 mb-0 span-divider">/</span>
                <strong class="current-page">cookie-policy</strong>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="col-md-12 text-center">
            <h3 class="info-title">Cookie Policy in englisch</h3>
        <p class="info-text">
            This website uses cookies. Cookies are small text files that are stored in your computer when you visit this website.
            computer permanently or temporarily. The purpose of cookies is in particular the analysis of the
            Use of this website for statistical analysis and continuous improvement.
            You can deactivate cookies in your browser settings at any time, either in part or in full.
            If cookies are deactivated, you may no longer have access to all the functions of this website

        </p>

        <h3 class="info-title">Cookie Policy in Deutsch</h3>
        <p class="info-text">
            Diese Website verwendet Cookies. Cookies sind kleine Textdateien, die beim Besuch dieser Website in Ihrem
            Computer dauerhaft oder temporär gespeichert werden. Zweck der Cookies ist insbesondere die Analyse der
            Nutzung dieser Website zur statistischen Auswertung sowie für kontinuierliche Verbesserungen.
            In Ihrem Browser können Sie Cookies in den Einstellungen jederzeit ganz oder teilweise deaktivieren.
            Bei deaktivierten Cookies stehen Ihnen allenfalls nicht mehr alle Funktionen dieser Website zur Verfügung
        </p>

    </div>
</div>
<br>
{% endblock %}

templates/impressum.html
{% extends "base.html" %}
{% block head_title %}
impressum - amphibian.ch
{% endblock %}

{% block extra_head %}
<meta name="description" property="og:description" content="Impressum of amphibian.ch">

{% endblock extra_head %}

{% block content %}

<div class="container">
    <h2>impressum</h2>
</div>

<div class="">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">home</a>
                <span class="mx-2 mb-0 span-divider">/</span>
                <strong class="current-page">impressum</strong>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="col-md-12 text-center">
        <p class="info-title">
            <strong>
                Kontakt-Adresse
            </strong>
        </p>

        <p class="info-text">
            amphibian.ch
            <br/>
            Fabian H&auml;fliger
            <br/>
            Talacherstrasse 7
            <br/>
        6340 Baar
            <br/>
            Schweiz
        </p>

        <p class="info-title">
            <strong>E-Mail:</strong>
        </p>

        <p class="info-text">
            fabian.haefi@gmail.com
        </p>


        <p class="info-title">
                <strong>Vertretungsberechtigte Person(en)</strong>
        </p>

        <p class="info-text">
            Fabian H&auml;fliger, Inhaber
        </p>

        <p class="info-title">
                <strong>Haftungsausschluss</strong>
        </p>
        <p class="info-text">
            Der Autor &uuml;bernimmt keinerlei Gew&auml;hr hinsichtlich der inhaltlichen Richtigkeit, Genauigkeit,
                Aktualit&auml;t, Zuverl&auml;ssigkeit und Vollst&auml;ndigkeit der Informationen.
        </p>

        <p class="info-text">Haftungsanspr&uuml;che
        gegen den Autor wegen Sch&auml;den materieller oder immaterieller Art, welche aus dem Zugriff oder der Nutzung
        bzw. Nichtnutzung der ver&ouml;ffentlichten Informationen, durch Missbrauch der Verbindung oder durch technische
        St&ouml;rungen entstanden sind, werden ausgeschlossen.
        </p>

        <p class="info-text">
            Alle Angebote sind unverbindlich. Der Autor
        beh&auml;lt es sich ausdr&uuml;cklich vor, Teile der Seiten oder das gesamte Angebot ohne besondere
        Ank&uuml;ndigung zu ver&auml;ndern, zu erg&auml;nzen, zu l&ouml;schen oder die Ver&ouml;ffentlichung zeitweise
        oder endg&uuml;ltig einzustellen.
        </p>

        <p class="info-title">
            <strong>Haftungsausschluss f&uuml;r Links</strong>
        </p>
        <p class="info-text">Verweise und Links auf Webseiten Dritter liegen ausserhalb unseres Verantwortungsbereichs.
            Es wird jegliche Verantwortung f&uuml;r solche Webseiten abgelehnt. Der Zugriff und die Nutzung solcher
            Webseiten erfolgen auf eigene Gefahr des jeweiligen Nutzers.
        </p>
        <p>
            <strong>
                Urheberrechte
            </strong>
        </p>

        <p class="info-text">
            Die Urheber- und alle anderen Rechte an Inhalten, Bildern, Fotos oder anderen Dateien auf dieser Website,
        geh&ouml;ren ausschliesslich
            <strong>
                Fabian H&auml;fliger
            </strong>
            oder den speziell genannten Rechteinhabern. F&uuml;r die Reproduktion jeglicher Elemente ist die
            schriftliche Zustimmung des Urheberrechtstr&auml;gers im Voraus einzuholen.
        </p>
        <br/>
        <p class="info-text">
            Quelle: <a href="https://www.swissanwalt.ch" target="_blank" rel="noopener">SwissAnwalt</a>
        </p>
    </div>
</div>
<br>
{% endblock %}

templates/licence.html
{% extends "base.html" %}
{% block head_title %}
licences - amphibian.ch
{% endblock %}

{% block extra_head %}
<meta name="description" property="og:description" content="Find out about our licensing model">
{% endblock extra_head %}

{% block content %}
<div class="container">
    <h2>licences</h2>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12 mb-0">
            <a href="{% url 'home' %}">home</a>
            <span class="mx-2 mb-0 span-divider">/</span>
            <strong class="current-page">licences</strong>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-12 mb-0">
            <p class="info-text">Below are the licences that we are offering. If you have any question regarding our licences, feel free to <a href="{% url 'contact' %}">contact</a> us</p>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card-group">
                <div class="card text-center bootstrap-overrides-card">
                    <div class="card-body">
                        <h5 class="card-title bootstrap-override-cart-title">WAV-Lease</h5>
                        <h6 class="bootstrap-override-cart-subtitle">
                            USD 50.- per unit
                        </h6>
                        <ul class="list-group">
                            <li class="list-group-item bootstrap-override-list-group-item">WAV Version</li>
                            <li class="list-group-item bootstrap-override-list-group-item">MP3-Version on request</li>
                            <li class="list-group-item bootstrap-override-list-group-item">One Commercial Use (Mixtape,
                            iTunes, Radio, etc)</li>
                            <li class="list-group-item bootstrap-override-list-group-item">Royalty Free</li>
                            <li class="list-group-item bootstrap-override-list-group-item">amphibian.ch retains full rights</li>
                        </ul>
                    </div>
                </div>
                <div class="card text-center bootstrap-overrides-card">
                    <div class="card-body">
                        <h5 class="card-title bootstrap-override-cart-title">Unlimited Lease</h5>
                        <h6 class="bootstrap-override-cart-subtitle">
                            USD 250.- per unit
                        </h6>
                        <ul class="list-group">
                            <li class="list-group-item bootstrap-override-list-group-item">Trackouts</li>
                            <li class="list-group-item bootstrap-override-list-group-item">WAV Lease</li>
                            <li class="list-group-item bootstrap-override-list-group-item">Royalty Free</li>
                            <li class="list-group-item bootstrap-override-list-group-item">Unlimited Commercial Use</li>
                            <li class="list-group-item bootstrap-override-list-group-item">amphibian.ch retains full rights</li>
                            <li class="list-group-item bootstrap-override-list-group-item">Unlimited commercial distribution</li>
                        </ul>
                    </div>
                </div>
                <div class="card text-center bootstrap-overrides-card">
                    <div class="card-body bootstrap-override-cart-title">
                        <h5 class="card-title bootstrap-override-cart-title">Exclusive</h5>
                        <p class="card-body info-text">We are always open for selling our music exclusively to artist. Make us an offer.</p>
                        <a href="{% url 'contact' %}" class="btn btn-block amphibian-button-info">get in contact</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>
{% endblock %}

templates/order.html
{% extends "base.html" %}
{% block head_title %}
order - amphibian.ch
{% endblock %}

{% block extra_head %}
<meta name="description" property="og:description" content="Find your orders here">
{% endblock extra_head %}


{% block content %}
<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <a href="{% url 'profile' %}">Back to profile</a>
                <br>
                <hr class="horizontal-divider">
                <br>
                <div class="">
                    <div class="">
                        <h5 class="card-title font-normal-white">Order: #{{order.reference_number }}
                        </h5>
                        <h6 class="card-subtitle mb-2 text-muted">Ordered on: {{ order.ordered_date }}</h6>
                        <hr />
                        <h5 class="card-title font-normal-white">
                            Your Orders
                        </h5>
                        <div class="site-block-table">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Total</th>
                                        <th>Files</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for item in order.items.all %}
                                <tr>
                                    <td class="font-medium-white">{{ item.product.title }}</td>
                                    <td class="font-medium-white">${{ item.get_total_item_price }}</td>
                                    <td>
                                        <a href="{{ item.product.file.url }}" download>WAV</a>
                                        {% if item.is_unlimited_lease %}
                                        <span class="mx-2 mb-0 span-divider">/</span>
                                        <a href="{{ item.product.trackout_files.url }}" download>Trackout</a>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td>Subtotal</td>
                                    <td>${{ order.get_subtotal }}</td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                 <tr>
                                    <td>Total</td>
                                    <td>${{order.get_total}}</td>
                                     <td></td>
                                     <td></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block head_title %}
profile - amphibian.ch
{% endblock %}

{% block extra_head %}
<meta name="description" property="og:description" content="Find your profile information and completed orders on amphibian.ch">
{% endblock extra_head %}


{% block content %}
<div class="site-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h5 class="font-normal-white">{{ request.user.email }}
                    <a href="{% url 'account_logout' %}"><strong class="float-right">Logout</strong></a>
                </h5>
                <hr class="horizontal-divider">
                <h5 class="font-normal-white">
                    Your Orders
                </h5>
                <div class="site-block-table">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Reference No.</th>
                            <th>Amount</th>
                            <th>Status</th>
                            <th>Files</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in orders %}
                        <tr>
                            <td><a href="{% url 'cart:order-detail' order.pk %}">#{{order.reference_number }}</a></td>
                            <td>${{ order.get_total }}</td>
                            <td>{% if order.ordered %}Paid{% else %}Not paid{% endif %}</td>
                            <td>{% for item in order.items.all %}
                                <a href="{{ item.product.file.url }}" download>WAV</a>
                                {% if item.is_unlimited_lease %}
                                <span class="mx-2 mb-0 span-divider">/</span>
                                        <a href="{{ item.product.trackout_files.url }}" download>Trackout</a>
                                    {% endif %}
                                {% endfor %}
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="4">You haven't made any orders</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/scripts.html
{% load static %}
<script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
<script src="{% static 'app.js' %}"></script>

templates/terms-and-condition.html
{% extends "base.html" %}
{% block head_title %}
terms and conditions - amphibian.ch
{% endblock %}

{% block extra_head %}
<meta name="description" property="og:description" content="Find out about our terms and conditions on amphibian.ch">
{% endblock extra_head %}

{% block content %}

<div class="container">
    <h2>terms and conditions</h2>
</div>

<div class="">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href="{% url 'home' %}">home</a>
                <span class="mx-2 mb-0 span-divider">/</span>
                <strong class="current-page">terms and conditions</strong>
            </div>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="col-md-12 text-center">
        <h3>terms and conditions englisch</h3>
        <br>
        <p class="info-text">Please read the following document before using amphibian.ch.
            <br>
        Effective: 31. December 2020
        </p>
        <br>
        <h5 class="info-title">Intellectual property</h5>
        <p class="info-text">
            All content (logos, products and others) on this website is the legal property of amphibian.ch and business
            partners, unless otherwise noted.
        </p>
        <br>
        <h5 class="info-title">Consent</h5>
        <p class="info-text">
            By using this website you accept the terms of use. If you do not agree to them, please do not use our
            website.
        </p>
        <br>
        <h5 class="info-title">Changes</h5>
        <p class="info-text">
            These terms and conditions are subject to change due to market, legal or other changes. It is therefore
            important that you as a user check the terms and conditions regularly.
        </p>
        <br>
        <h5 class="info-title">Legal matters</h5>
        <p class="info-text">
            Whether this website may be used in the country of origin of our users is not the responsibility
            of amphibian.ch.
        </p>
        <br>
        <h5 class="info-title">Refunds</h5>
        <p class="info-text">
            We do not grant refunds on granted purchases.
        </p>
        <hr class="horizontal-divider">
        <h3>Nutzungsbedinungen Deutsch</h3>
        <br>
        <p class="info-text">Bitte lesen Sie das folgende Dokument durch, bevor Sie amphibian.ch benutzen.
            <br>
        Gültig ab 31. December 2020
        </p>
        <br>
        <h5 class="info-title">Geistiges Eigentum</h5>
        <p class="info-text">
            Jeder Inhalt (Logos, Produkte und andere) auf dieser Webseite ist rechtliches Eigentum von amphibian.ch und
            Geschäftspartnern, sofern nicht anderweitig vermerkt.
        </p>
        <br>
        <h5 class="info-title">Einverständnis</h5>
        <p class="info-text">
            All content (logos, products and others) on this website is the legal property of amphibian.ch and business
            partners, unless otherwise noted.
        </p>
        <br>
        <h5 class="info-title">Änderungen</h5>
        <p class="info-text">
            Diese Bedingungen können in Hinblick auf Veränderungen im Markt sowie rechtlichen oder anderen Umständen
            geändert werden. Es ist deshalb wichtig, dass Sie als Nutzer die Bedinungen regelmässig überprüfen.
        </p>
        <br>
        <h5 class="info-title">Rechtliches</h5>
        <p class="info-text">
            Diese Bedingungen können in Hinblick auf Veränderungen im Markt sowie rechtlichen oder anderen Umständen
            geändert werden. Es ist deshalb wichtig, dass Sie als Nutzer die Bedinungen regelmässig überprüfen.
        </p>
        <br>
        <h5 class="info-title">Rückerstattungen</h5>
        <p class="info-text">
            Wir gewähren keine Rückerstattungen auf gewährte Einkäufe.
        </p>
    </div>
</div>
<br>
{% endblock %}